global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'dcss-api'
    static_configs:
      - targets:
          - 'app:9464'
          # For local docker-compose monitoring:
          # - 'host.docker.internal:9464'

  # - job_name: prometheus
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
